
# ros2 run slam_toolbox async_slam_toolbox_node \
#   --ros-args \
#   -p solver_plugin:=solver_plugins::CeresSolver \
#   -p ceres_linear_solver:=SPARSE_NORMAL_CHOLESKY \
#   -p ceres_preconditioner:=SCHUR_JACOBI \
#   -p ceres_trust_strategy:=LEVENBERG_MARQUARDT \
#   -p ceres_dogleg_type:=TRADITIONAL_DOGLEG \
#   -p ceres_loss_function:=None \
#   -p odom_frame:=odom \
#   -p map_frame:=map \
#   -p base_frame:=base_link \
#   -p scan_topic:=/scan \
#   -p use_map_saver:=true \
#   -p mode:=mapping \
#   -p debug_logging:=true \
#   -p throttle_scans:=1 \
#   -p transform_publish_period:=0.2 \
#   -p map_update_interval:=5.0 \
#   -p resolution:=0.05 \
#   -p max_laser_range:=20.0 \
#   -p minimum_time_interval:=0.5 \
#   -p transform_timeout:=0.2 \
#   -p tf_buffer_duration:=30.0 \
#   -p stack_size_to_use:=43000000 \
#   -p enable_interactive_mode:=true \
#   -p use_scan_matching:=true \
#   -p use_scan_barycenter:=true \
#   -p minimum_travel_distance:=0.5 \
#   -p minimum_travel_heading:=0.5 \
#   -p scan_buffer_size:=10 \
#   -p scan_buffer_maximum_scan_distance:=10.0 \
#   -p link_match_minimum_response_fine:=0.1 \
#   -p link_scan_maximum_distance:=1.5 \
#   -p loop_search_maximum_distance:=3.0 \
#   -p do_loop_closing:=true \
#   -p loop_match_minimum_chain_size:=10 \
#   -p loop_match_maximum_variance_coarse:=3.0 \
#   -p loop_match_minimum_response_coarse:=0.35 \
#   -p loop_match_minimum_response_fine:=0.45 \
#   -p correlation_search_space_dimension:=0.5 \
#   -p correlation_search_space_resolution:=0.01 \
#   -p correlation_search_space_smear_deviation:=0.1 \
#   -p loop_search_space_dimension:=8.0 \
#   -p loop_search_space_resolution:=0.05 \
#   -p loop_search_space_smear_deviation:=0.03 \
#   -p distance_variance_penalty:=0.5 \
#   -p angle_variance_penalty:=1.0 \
#   -p fine_search_angle_offset:=0.00349 \
#   -p coarse_search_angle_offset:=0.349 \
#   -p coarse_angle_resolution:=0.0349 \
#   -p minimum_angle_penalty:=0.9 \
#   -p minimum_distance_penalty:=0.5 \
#   -p use_response_expansion:=true \
#   -p min_pass_through:=2 \
#   -p occupancy_threshold:=0.1

slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Parameters
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    use_map_saver: true
    mode: mapping #localization

    # if you'd like to immediately start continuing a map at a given pose
    # or at the dock, but they are mutually exclusive, if pose is given
    # will use pose
    #map_file_name: test_steve
    # map_start_pose: [0.0, 0.0, 0.0]
    #map_start_at_dock: true

    debug_logging: true
    throttle_scans: 1
    transform_publish_period: 0.2 #if 0 never publishes odometry
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 20.0 #for rastering images
    minimum_time_interval: 0.5
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 43000000 #// program needs a larger stack size to serialize large maps
    enable_interactive_mode: true

    # General Parameters
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Correlation Parameters - Correlation Parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Correlation Parameters - Loop Closure Parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan Matcher Parameters
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0

    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1
